##########################
# Instructions are listed in the "ReadMe.txt" file
# Enter your information after each colon below ": " make sure there is a space after the colon ": "
# Be very careful do not make any other changes
# Edit the website text in the file called "websitetext.md"
# Important: Add your privacy policy in the "privacypolicy.md" file
# In this file only, anything after a number sign "#" are comments, ignored by the computer
##########################

title: Your Company Name LLC
author: Frank MacLeon
photo: "/photo.jpg" 

email: fmacleon@yahoo.com
facebook_username: frank.macleon
twitter_username: 
youtube_username: 
flickr_username: 
dribbble_username: 
github_username: fmcsllc
instagram_username: 
linkedin_username: frank-macleon-6a001b38
pinterest_username: 

url: "" # custom URL if purchased, e.g. "example.com"
baseurl: "/easytest" # GitHub repository name, leave blank for main or use e.g. "/yourcompanyname"

######## Add your social media user names to activate icons
#social-twitter: fmacleon # add your Twitter handle, none, iconOnly
#social-facebook: iconOnly # add your Facebook handle, none, iconOnly
#social-github: none # add your Github handle, none, iconOnly
#social-linkedin: iconOnly # add your Linkedin handle
#pinterest_username: iconOnly 
#youtube_username: iconOnly
#instagram_username: iconOnly 
#etsy_username: iconOnly
#email_address: fmacleon@yahoo.com # add your Email address, none, iconOnly
#email_cc: #"cc=fmacleon@yahoo.com&"
#email_firstName: website owner # used to customize email link, send [me] an email
#email_subject: About your products or services # email subject line on main page
# Other Social accounts, ~/gems/gems/minima-2.5.1/_includes/social.html
#dribbble_username: false # not coded yet
#flickr_username: false # not coded yet
#mst.username: false # not coded yet
#mst.instance: false # not coded yet
#googleplus_username: false # not coded yet
#rss: false # not coded yet

############## ADVANCED SETTINGS ##############################
# Build settings
theme: minima
#plugins:
#  - jekyll-feed

easyBackground: #053574

#Theme options:
#jekyll-theme-architect
#jekyll-theme-cayman
#jekyll-theme-dinky
#jekyll-theme-hacker
#jekyll-theme-leap-day
#jekyll-theme-merlot
#jekyll-theme-midnight
#minima
#jekyll-theme-minimal
#jekyll-theme-modernist
#jekyll-theme-slate
#jekyll-theme-tactile
#jekyll-theme-time-machine

############################################################
# excludes files from _site directory
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "*.sh", "*.txt", "FML_notes", "FML_Notes", "*.odt", "*.txt"]
# #################################################################################
# LICENSE:
# MIT License
#
# Copyright (c) 2022 FMCS LLC
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# #################################################################################